export const UNSW_LOCATIONS = [
  'Main Library',
  'Quadrangle (E15)',
  'Ainsworth Building (J17)',
  'Electrical Engineering (G17)',
  'Mathews Building (F23)',
  'Law Building (F8)',
  'Biological Sciences (E26)',
  'Physics Building (D17)',
  'Computer Science & Eng. (K17)',
  'Central Lecture Block (F14)',
  'Tyree Energy Technologies (H6)',
  'John Niland Scientia (E8)',
  'Rupert Myers Building (E19)',
  'Red Centre',
  'Arc @ UNSW (C22)',
  'Roundhouse (E6)',
  'ASB (Australian School of Business)',
  'Colombo Theatres (C)',
  'Rex Vowels Building',
  'Chemical Sciences Building',
];
